Feature/teke order hero
ASyrotenko/command-project-html-css pull request #11
Opened 2022-09-10 13:49 UTC by NataliiaVlasenko

add section  Feature/teke order hero

2022-09-10 17:46 UTC, MakiievOleksandr commented
подивився, потрібно виправити ситуацію з декором. та контентом на мобільній версії

2022-09-10 19:37 UTC, ASyrotenko requested changes
Zoom

2022-09-11 12:07 UTC, vitekkez approved these changes
ok

2022-09-11 14:53 UTC, ASyrotenko approved these changes

2022-09-11 14:54 UTC, merged