Footer
ASyrotenko/command-project-html-css pull request #16
Opened 2022-09-11 06:04 UTC by HannaGolovashkina

finish, please check it

2022-09-11 08:25 UTC, NataliiaVlasenko requested changes
address, media@ (tg)

2022-09-11 10:31 UTC, YevheniiaVier commented
<div class="footer-conteiner"> - тут повинен бути загальний клас з common - container - футер зараз без контейнеру.

2022-09-11 15:23 UTC, HannaGolovashkina commented
Додала окремо контейнер і марджини

2022-09-11 20:16 UTC, YevheniiaVier approved these changes
initial check done

2022-09-12 17:22 UTC, ASyrotenko approved these changes

2022-09-12 17:23 UTC, merged